server:
  port: 7123

spring:
  profiles:
    active: local
  application:
    name: test_eureka
  config:
    import: optional:configserver:http://localhost:8777
---
spring:
  application:
    name: test_eureka
  config:
    activate:
      on-profile: local
logging:
  level:
    '[com.example.demo]': debug
eureka:  client:    register-with-eureka: false
    fetch-registry: false
    service-url:      defaultZone: http://localhost:7123/eureka